Odoo Server Error
Traceback (most recent call last):
  File "C:\Program Files\Odoo 14\server\odoo\tools\convert.py", line 677, in _tag_root
    f(rec)
  File "C:\Program Files\Odoo 14\server\odoo\tools\convert.py", line 580, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "C:\Program Files\Odoo 14\server\odoo\models.py", line 4203, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "C:\Program Files\Odoo 14\server\odoo\models.py", line 4132, in _load_records_create
    return self.create(values)
  File "<decorator-gen-42>", line 2, in create
  File "C:\Program Files\Odoo 14\server\odoo\api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "C:\Program Files\Odoo 14\server\odoo\addons\base\models\ir_ui_view.py", line 482, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-64>", line 2, in create
  File "C:\Program Files\Odoo 14\server\odoo\api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "C:\Program Files\Odoo 14\server\odoo\addons\base\models\ir_fields.py", line 533, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "C:\Program Files\Odoo 14\server\odoo\api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "C:\Program Files\Odoo 14\server\odoo\models.py", line 3893, in create
    fields[0].determine_inverse(batch_recs)
  File "C:\Program Files\Odoo 14\server\odoo\fields.py", line 1147, in determine_inverse
    getattr(records, self.inverse)()
  File "C:\Program Files\Odoo 14\server\odoo\addons\base\models\ir_ui_view.py", line 300, in _inverse_arch
    view.write(data)
  File "C:\Program Files\Odoo 14\server\odoo\addons\base\models\ir_ui_view.py", line 500, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "C:\Program Files\Odoo 14\server\odoo\models.py", line 3682, in write
    real_recs._validate_fields(set(vals) - set(inverse_fields))
  File "C:\Program Files\Odoo 14\server\odoo\models.py", line 1250, in _validate_fields
    check(self)
  File "C:\Program Files\Odoo 14\server\odoo\addons\base\models\ir_ui_view.py", line 411, in _check_xml
    )).with_traceback(e.__traceback__) from None
  File "C:\Program Files\Odoo 14\server\odoo\addons\base\models\ir_ui_view.py", line 391, in _check_xml
    view.postprocess_and_fields(view_doc, validate=True)
  File "C:\Program Files\Odoo 14\server\odoo\addons\base\models\ir_ui_view.py", line 851, in postprocess_and_fields
    arch, name_manager = self._postprocess_view(node, model, validate=validate)
  File "C:\Program Files\Odoo 14\server\odoo\addons\base\models\ir_ui_view.py", line 863, in _postprocess_view
    self.postprocess(node, [], editable, name_manager)
  File "C:\Program Files\Odoo 14\server\odoo\addons\base\models\ir_ui_view.py", line 963, in postprocess
    self.postprocess(child, current_node_path, node_info['editable'], name_manager)
  File "C:\Program Files\Odoo 14\server\odoo\addons\base\models\ir_ui_view.py", line 954, in postprocess
    validator(node, name_manager, node_info)
  File "C:\Program Files\Odoo 14\server\odoo\addons\base\models\ir_ui_view.py", line 1090, in _validate_tag_field
    self.handle_view_error(msg)
  File "C:\Program Files\Odoo 14\server\odoo\addons\base\models\ir_ui_view.py", line 673, in handle_view_error
    raise ValueError(formatted_message).with_traceback(from_traceback) from from_exception
odoo.exceptions.ValidationError: Error while validating view:

Field "color_id" does not exist in model "mrp.production"

View name: view.production.form.inherit
Error context:
 view: ir.ui.view(3620,)
 xmlid: view_production_form_inherit
 view.model: mrp.production
 view.parent: ir.ui.view(2095,)
 file: c:\program files\odoo 14\server\odoo\custom_addons\todo_app\views\todo_view.xml


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\Odoo 14\server\odoo\addons\base\models\ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "C:\Program Files\Odoo 14\server\odoo\http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files\Odoo 14\server\odoo\http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files\Odoo 14\server\odoo\service\model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files\Odoo 14\server\odoo\http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files\Odoo 14\server\odoo\http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files\Odoo 14\server\odoo\http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files\Odoo 14\server\odoo\addons\web\controllers\main.py", line 1381, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "C:\Program Files\Odoo 14\server\odoo\addons\web\controllers\main.py", line 1369, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files\Odoo 14\server\odoo\api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "C:\Program Files\Odoo 14\server\odoo\api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-71>", line 2, in button_immediate_install
  File "C:\Program Files\Odoo 14\server\odoo\addons\base\models\ir_module.py", line 73, in check_and_log
    return method(self, *args, **kwargs)
  File "C:\Program Files\Odoo 14\server\odoo\addons\base\models\ir_module.py", line 474, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "C:\Program Files\Odoo 14\server\odoo\addons\base\models\ir_module.py", line 592, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "C:\Program Files\Odoo 14\server\odoo\modules\registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "C:\Program Files\Odoo 14\server\odoo\modules\loading.py", line 455, in load_modules
    loaded_modules, update_module, models_to_check)
  File "C:\Program Files\Odoo 14\server\odoo\modules\loading.py", line 348, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "C:\Program Files\Odoo 14\server\odoo\modules\loading.py", line 221, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "C:\Program Files\Odoo 14\server\odoo\modules\loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "C:\Program Files\Odoo 14\server\odoo\tools\convert.py", line 733, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "C:\Program Files\Odoo 14\server\odoo\tools\convert.py", line 799, in convert_xml_import
    obj.parse(doc.getroot())
  File "C:\Program Files\Odoo 14\server\odoo\tools\convert.py", line 719, in parse
    self._tag_root(de)
  File "C:\Program Files\Odoo 14\server\odoo\tools\convert.py", line 677, in _tag_root
    f(rec)
  File "C:\Program Files\Odoo 14\server\odoo\tools\convert.py", line 685, in _tag_root
    )) from e
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\Odoo 14\server\odoo\http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files\Odoo 14\server\odoo\http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.tools.convert.ParseError: while parsing file:/c:/program%20files/odoo%2014/server/odoo/custom_addons/todo_app/views/todo_view.xml:3, near
<record id="view_production_form_inherit" model="ir.ui.view">
            <field name="name">view.production.form.inherit</field>
            <field name="model">mrp.production</field>
            <field name="inherit_id" ref="mrp.mrp_production_tree_view"/>
            <field name="arch" type="html">
                <xpath expr="//field[@name='product_id']" position="after">
                    <field name="color_id" optional="show"/>
                    <field name="material_id" optional="show"/>
                </xpath>
            </field>
        </record>
